version: "3.8"
services:
  mysql:
    image: mysql:8
    container_name: mysql_apotek
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: apotek
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
